/**
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS-IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// This file is automatically generated

package com.google.livingstories.plugins.wordpress.livingstorypropertymanager.client.i18n;


/**
 * Interface to represent the constants contained in resource bundle:
 * 	'ClientConstants.properties'.
 */
public interface ClientConstants extends com.google.gwt.i18n.client.Constants {
  /**
   * Translated "High".
   * 
   * @return translated "High"
   */
  @DefaultStringValue("High")
  @Key("importanceHigh")
  String importanceHigh();

  /**
   * Translated "Low".
   * 
   * @return translated "Low"
   */
  @DefaultStringValue("Low")
  @Key("importanceLow")
  String importanceLow();

  /**
   * Translated "Medium".
   * 
   * @return translated "Medium"
   */
  @DefaultStringValue("Medium")
  @Key("importanceMedium")
  String importanceMedium();
  
  /**
   * Google Maps API key used to input and display location. 
   */
  @Key("mapsKey")
  String mapsKey();
}
