/**
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS-IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// This file is automatically generated

package com.google.livingstories.plugins.wordpress.livingstorypropertymanager.client.i18n;

import com.google.gwt.i18n.client.LocalizableResource.DefaultLocale;
import com.google.gwt.i18n.client.LocalizableResource.Generate;

/**
 * Interface to represent the messages contained in resource bundle: ClientMessages.properties.
 * IMPORTANT NOTE - unlike most of our other files, which are automatically synced _from_ their
 * source .properties file, this .java file is the canonical version of these messages.
 * We use the @Generate annotation below to autogenerate an appropriate .properties file
 * that corresponds to this .java file.
 */
@DefaultLocale("en")
@Generate(format = "com.google.gwt.i18n.rebind.format.PropertiesFormat", locales = "en")
public interface ClientMessages extends com.google.gwt.i18n.client.Messages {
  // Empty for now. Add any messages with arguments to be internationalized here.
}
